project_id = "continental"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = ["./seed/*.sql"]

[auth]
enabled = true
enable_signup = false
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]

[realtime]
enabled = true

[storage]
enabled = false
